apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      version: "6.4.0"
  template:
    metadata:
      labels:
        app: kibana
        version: "6.4.0"
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.4.0
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elastic:9200/"
        ports:
        - containerPort: 5601
---
kind: Service
apiVersion: v1
metadata:
  name: kibana
spec:
  type: NodePort
  selector:
    app: kibana
    version: "6.4.0"
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
